publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 10

    goal_names: ["pos1", "pos2", "pos3"]
    pos1: [-0.785, -0.785, -0.785, -0.785, -0.785, -0.785]
    pos2: [-0.385, -0.385, -0.385, -0.385, -0.385, -0.385]
    pos3: [-0.185, -0.185, -0.185, -0.185, -0.185, -0.185]

    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    check_starting_point: false
